name: Catalogue
main: com.commandblockguy.catalogue.Catalogue
version: 1.0
database: true
commands:
  catalogue:
    description: Your description
    usage: /catalogue (item)
permissions:
  catalogue.*:
    description: Gives access to all catalogue commands
    children:
      catalogue.gui: true
      catalogue.register: true